FROM python:3.10-slim

ENV REDIS_URL redis://redis:6379/1

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0

COPY . /app
WORKDIR /app

RUN pip install --no-cache-dir -r requirements.txt
