apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-simulation-worker

spec:
  replicas: {{ .Values.simulationWorkerReplicaCount }}
  selector:
    matchLabels:
      app: celery-simulation-worker

  template:
    metadata:
      labels:
        app: celery-simulation-worker
        backend: redis-app
        database: mongo-app
    spec:
      containers:
        - name: celery-simulation-worker-container
          image: {{ .Values.mtpWorkerImage }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - celery -A celery_worker worker -Q simulation_queue --concurrency=1
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-app-service:27017/"
            - name: CELERY_BROKER_URL
              value: "redis://redis-app-service:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis-app-service:6379/0"
      imagePullSecrets:
        - name: mtp-ecr-registry