apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-process-worker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-process-worker

  template:
    metadata:
      labels:
        app: celery-process-worker
        backend: redis-app
        database: mongo-app
    spec:
      containers:
        - name: celery-process-worker-container
          image: celery-worker-image
          imagePullPolicy: Never
          command: ["/bin/sh", "-c"]
          args:
            - celery -A celery_worker worker -Q process_queue
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-app-service:27017/"
            - name: CELERY_BROKER_URL
              value: "redis://redis-app-service:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis-app-service:6379/0"