apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app
        backend: redis-app
        database: mongo-app
    spec:
      containers:
        - name: flask-app-container
          image: {{ .Values.mtpDashboardImage }}
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_URL
              value: "mongodb://mongo-app-service:27017/"
            - name: CELERY_BROKER_URL
              value: "redis://redis-app-service:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis-app-service:6379/0"
          ports:
            - containerPort: 5000
              protocol: TCP
      imagePullSecrets:
        - name: mtp-ecr-registry
